apiVersion: v1
kind: Service
metadata:
  name: portal-news-frontend-service
spec:
  type: NodePort
  selector:
    app: portal-news-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30134
